### ISSUE TITLE
Cutting a new release (Orphan.hs issue)

### ISSUE THREAD

**Issue by YoEight** [alphaHeavy/protobuf#29]
Greetings, 

In my way to migrate my lib to GHC 8.0.1 I got this error.

```
    Configuring protobuf-0.2.1.0...
    Building protobuf-0.2.1.0...
    Preprocessing library protobuf-0.2.1.0...
    [1 of 8] Compiling Data.ProtocolBuffers.Orphans ( src/Data/ProtocolBuffers/Orphans.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/Data/ProtocolBuffers/Orphans.o )
    
    /tmp/stack14565/protobuf-0.2.1.0/src/Data/ProtocolBuffers/Orphans.hs:17:1: error:
        Duplicate instance declarations:
          instance Foldable Last
            -- Defined at src/Data/ProtocolBuffers/Orphans.hs:17:1
          instance Foldable Last -- Defined in ‘Data.Foldable’

```

It appears that issue doesn't occur on `protobuf` master.

Is it possible to cut and upload a new release onto Hackage (and also indicating in Stackage repo `protobuf` builds with GHC 8.0.1) ?

Thanks for your time.

Yorick

**Comment by YoEight** [comment]
Any news on that front ?

**Comment by NathanHowell** [comment]
@YoEight the first notification got lost in my inbox over the holiday weekend, sorry about that. I will work on it either tonight or Monday morning.

**Comment by YoEight** [comment]
No problem, thank you very much !

**Comment by NathanHowell** [comment]
I backported these fixes to the 0.2 branch and cut a new release: http://hackage.haskell.org/package/protobuf-0.2.1.1

**Comment by YoEight** [comment]
Thanks, works for me
